# Do not edit this file. It is automatically generated by https://www.oliverdavies.uk/build-configs.
{
  description = "A Nix Flake for build-configs";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { nixpkgs, ... }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};

      inherit (pkgs) just mkShell php82 php82Packages;

      php = php82;
      phpPackages = php82Packages;
    in {
      devShells.${system}.default =
        mkShell { buildInputs = [ just php phpPackages.composer ]; };
    };
}
